PagerDuty/backstage-plugin

.github/workflows/build.yml
.github/workflows/publish.yml
.husky/commit-msg
commitlint.config.js
package.json
release.config.js
yarn.lock

Adding automated versioning by leveraging conventional commits and GitHub extension.
- Enforces conventional commits with git pre-commit hook
- Automatically bumps the version depending on type of commit
- generates release notes
- publishes a new release in GitHub and NPM
Closes #1.

Adding automated versioning for package publishing

---

.github/workflows/publish.yml
release.config.js

:green_heart: replacing npm with yarn in semantic release config

replacing npm with yarn in semantic release config

---

release.config.js

:pencil2: fixing a typo on yarn package used in semantic release config
closes #8

fixing a typo on yarn package used in semantic release config

---

src/components/ChangeEvents/ChangeEvents.tsx
src/components/Incident/Incidents.tsx

Adding some consistency to the UI.
- :lipstick: removing subheaders from lists to avoid title duplication

Removing subheaders from lists

---

.github/workflows/publish.yml

Semantic Release cannot generate new package from PR. It needs to run on "push".

updating trigger to push to version and package to be generated and published. 

---

yarn.lock

Reverts PagerDuty/backstage-plugin#27

Revert "chore(deps): bump browserify-sign from 4.2.1 to 4.2.2"

---

dev/mockPagerDutyApi.ts
src/api/client.test.ts
src/components/EntityPagerDutyCard/index.test.tsx
src/components/Escalation/Escalation.test.tsx
src/components/Escalation/EscalationPolicy.tsx
src/components/Escalation/EscalationUser.tsx
src/components/PagerDutyCard/index.test.tsx
src/components/types.ts

Current implementation lists all oncall users, on all escalation levels, for an escalation policy assigned to a specific service. This is how the PagerDuty API works currently.
**Problems:**
- If an escalation policy contains an oncall schedule, then the user currently on-call is returned. But if individual users are used instead all of them are listed.
- Same user might exist in different escalation levels which causes the same user to show up multiple times on the list.
- The current implementation doesn't use the gravatar image used in PagerDuty. It uses a dummy avatar icon for everyone.
**Proposed implementation:**
- List only users in escalation level 1 - these are the users that are actually oncall.
- Remove duplicate users from the oncall user list
- Add support for user profile …

fix: list only oncall users in plugin

---

dev/mockPagerDutyApi.ts
package.json
src/api/client.test.ts
src/api/client.ts
src/api/index.ts
src/api/types.ts
src/components/ChangeEvents/ChangeEventListItem.tsx
src/components/ChangeEvents/ChangeEvents.test.tsx
src/components/EntityPagerDutyCard/index.test.tsx
src/components/Escalation/Escalation.test.tsx
src/components/Escalation/EscalationPolicy.tsx
src/components/Escalation/EscalationUser.tsx
src/components/Escalation/EscalationUsersEmptyState.tsx
src/components/Incident/IncidentListItem.tsx
src/components/Incident/Incidents.test.tsx
src/components/PagerDutyCard/index.test.tsx
src/components/index.ts
src/components/types.ts
yarn.lock

This PR moves the direct REST API calls from the frontend component to the backend. Instead of leveraging the Backstage proxy to make direct API calls to PagerDuty the calls are made now to the backend plugin. 
This removes the dependency on the proxy and prevents other plugins from using the PagerDuty proxy configuration to call PagerDuty APIs for other purposes which raises few security concerns.
This PR also fixes an issue with the on-call users not showing up (#58).
**Issue number:** #37.
**Disclaimer:** We value your time and bandwidth. As such, any pull requests created on non-triaged issues might not be …

feat: migrate api calls

---

package.json
yarn.lock

This PR bumps the version of @pagerduty/backstage-plugin-common to version 0.0.2. Version 0.0.1 had a misconfiguration that was forcing the backend plugin to load it as an ES6 module and while that's supported for the frontend it is not yet fully supported for backend plugins.
This upgrade syncs the version of the common package between frontend and backend plugins.

chore(deps): bumping up common package version to latest

---

config.d.ts

Removes the `pagerDuty.apiToken` and `pagerDuty.oauth` configuration definitions from this repository as they should be treated as secret config and this frontend plugin does not need to know about them.
See https://github.com/PagerDuty/backstage-plugin-backend/pull/36 for a related PR to mark those configuration values as secret.

fix: remove config definitions that are secret

---

src/components/EntityPagerDutyCard/index.test.tsx
src/components/PagerDutyCard/StatusCard.tsx
src/components/PagerDutyCard/index.test.tsx
src/components/PagerDutyCard/index.tsx

This PR introduces a behaviour change when the `integration key` is missing from an entity configuration. Currently the behaviour is to disable the button but keep it on the screen. 
After discussing the plugin with several customers, many shared with us that they don't want people to manually create incidents from Backstage as incidents are automatically created from alerts. Therefore we decided to remove the button if the integration key is not provided as part of the entity configuration, like we already do when the `readonly` parameter is passed to the PagerDutyCard.
This also allows us to save some valuable space in the PagerDutyCard.
**Issue number:** #67 
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …

feat: hide trigger incident on missing integration key

---

src/components/EntityPagerDutyCard/index.test.tsx
src/components/EntityPagerDutyCard/index.tsx
src/components/PagerDutyCard/index.tsx

This PR introduces a new `PagerDutyCard` option (_disableOnCall_) that allows users to completely hide the on-call section of the card. This feature was requested by several customers. 
The on-call section will still be shown by default making this an opt-in feature.
**Issue number:** #68 

feat: hide on-call information

---

README.md
src/api/client.test.ts

This corrects the `it()` description associated with the PagerDuty API client's handling of generic non-OK HTTP responses that are not 401s, 403s, or 404s. Previously, the test case claimed the client throws `NotFoundError`s in such cases. This is not true; the client throws a generic descriptive error in such cases.
Thanks!
**Issue number:** (e.g. #123)

fix: correct client test case description

---

src/components/TriggerDialog/TriggerDialog.tsx

This PR fixes an issue reported in #103 that was allowing users to trigger incidents without filling in the description because the state was being wrongly kept in memory.
**Issue number:** #103 

fix: ensures incident description state is cleaned after an incident is triggered

---

README.md

This PR adds the new mapping capability to the README.md file. 
**Issue number:** #80 

docs: update readme with mapping capability

---

config.d.ts
package.json
src/api/client.ts
src/api/types.ts
src/components/ChangeEvents/ChangeEvents.tsx
src/components/Escalation/Escalation.test.tsx
src/components/Escalation/EscalationPolicy.tsx
src/components/Incident/Incidents.tsx
src/components/PagerDutyCard/index.tsx
src/components/PagerDutyCardCommon/StatusCard.tsx
src/components/PagerDutyPage/MappingTable.tsx
src/components/PagerDutySmallCard/index.tsx
src/components/constants.ts
src/components/pagerDutyEntity.ts
src/types.ts
yarn.lock

This PR introduces support for multi-account configuration. With this PR admins will be able to specify multiple PagerDuty accounts in the same Backstage instance. Support was added across all the components of the plugin:
- **Backend:** All API routes exposed take account as an optional parameter so you can create and query information from different PagerDuty Accounts. If admins leverage the Entity Mapping feature, the account is now persisted into the plugin database.
- **Scaffolder Actions:** When the scaffolder action is used on a template it now lists Escalation Policies from all accounts configured so the user can easily select the one they want. The Scaffolder action also outputs the account so it can be replaced in the `app-config.yaml` annotations.
- **Entity Processor:** If an …

feat: add support for multi-account

---

src/components/PagerDutyPage/MappingTable.tsx

This PR introduces a fix to the issue reported on #123 that prevents users from showing/hiding columns in the service mapping table on `PagerDutyPage`.
**Issue number:** #123 

fix: turned columnvisibility into a static object

---

src/components/PagerDutyPage/index.tsx

This PR disables PagerDuty option on service dependency syncing configuration in `PagerDutyPage`. There is a design option on Backstage that prevents us to fully replace or remove existing relations from an entity configuration file. For that reason we are not able to guarantee that proper behaviour of PagerDuty syncing to Backstage. 
Users can still choose to have Backstage as a main source, ou to use both Backstage and PagerDuty which will merge the two sets of service dependencies in both platforms and keep them in sync.
**Issue number:** N/A
**Disclaimer:** We value your time and bandwidth. As such, any pull …

refactor: disabled pagerduty option due to a design limitation on Backstage

---

src/components/PagerDutyPage/index.tsx

This PR enables the `PagerDuty` option in the PagerDutyPage component settings which allows users to set PagerDuty as their main source for syncing service dependencies to Backstage. 
This feature was disabled due to a limitation on version [0.3.0](https://github.com/PagerDuty/backstage-plugin-entity-processor/releases/tag/0.3.0) of `@pagerduty/backstage-plugin-entity-processor` which is now fixed and released on version [0.3.1](https://github.com/PagerDuty/backstage-plugin-entity-processor/releases/tag/0.3.1).
**Issue number:** N/A
**Disclaimer:** We value your time and bandwidth. As such, any pull requests created …

refactor: enable PagerDuty option on PagerDutyPage

---

src/components/PagerDutyPage/index.tsx

This PR enables the `PagerDuty` option in the PagerDutyPage component settings which allows users to set PagerDuty as their main source for syncing service dependencies to Backstage. 
This feature was disabled due to a limitation on version [0.3.0](https://github.com/PagerDuty/backstage-plugin-entity-processor/releases/tag/0.3.0) of `@pagerduty/backstage-plugin-entity-processor` which is now fixed and released on version [0.3.1](https://github.com/PagerDuty/backstage-plugin-entity-processor/releases/tag/0.3.1).

release: 0.15.1

---

.yarnrc.yml
package.json

The value of `backstage.pluginPackages` was incorrectly set to `pluginId` when it is supposed to represent all the packages that are a part of this plugin. This PR corrects this value and fixes an issue that prevents this plugin from being installed on certain backstage installations.
**Issue number:** N/A

fix: fix pluginPackages type

---

package.json
yarn.lock

In order to reduce the amount changes required to update dependent packages
relax the version requirements for @pagerduty/backstage-plugin-common
**Issue number:** N/A

fix: relax version pinning of @pagerduty/backstage-plugin-common

---

.yarnrc.yml
package.json
yarn.lock

This release includes a fix to the backage.pluginPackages variable in package.json that was preventing the plugin from being installed in certain installations of backstage

release: 0.15.2
